import os
import sys
import subprocess
import shutil
from pathlib import Path

def create_installer():
    print("Creating Windows Installer for Blackjack Card Counter...")
    
    # Install required packages
    print("Installing required packages...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-r", "requirements.txt"])
    subprocess.check_call([sys.executable, "-m", "pip", "install", "pyinstaller", "pywin32", "nsis"])
    
    # Clean previous builds
    print("Cleaning previous builds...")
    for folder in ["build", "dist", "installer"]:
        if os.path.exists(folder):
            shutil.rmtree(folder)
    
    # Create the executable
    print("Building executable...")
    subprocess.check_call([sys.executable, "-m", "PyInstaller", "blackjack.spec", "--noconfirm"])
    
    # Create installer directory structure
    print("Creating installer structure...")
    os.makedirs("installer", exist_ok=True)
    
    # Create NSIS script
    with open("installer/installer.nsi", "w") as f:
        f.write("""
; Blackjack Card Counter Installer
; Generated by create_installer.py

!include "MUI2.nsh"

; General
Name "Blackjack Card Counter"
OutFile "BlackjackCardCounter_Setup.exe"
InstallDir "$PROGRAMFILES\\BlackjackCardCounter"
InstallDirRegKey HKCU "Software\\BlackjackCardCounter" ""

; Request application privileges for Windows Vista and above
RequestExecutionLevel admin

; Interface Settings
!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}\\Contrib\\Graphics\\Icons\\modern-install.ico"

; Pages
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_LANGUAGE "English"

Section "MainSection" SEC01
  SetOutPath "$INSTDIR"
  SetOverwrite try
  
  ; Copy all files from dist/BlackjackCardCounter
  File /r "dist\\BlackjackCardCounter\\*.*"
  
  ; Create start menu shortcut
  CreateDirectory "$SMPROGRAMS\\BlackjackCardCounter"
  CreateShortCut "$SMPROGRAMS\\BlackjackCardCounter\\Blackjack Card Counter.lnk" "$INSTDIR\\BlackjackCardCounter.exe"
  CreateShortCut "$DESKTOP\\Blackjack Card Counter.lnk" "$INSTDIR\\BlackjackCardCounter.exe"
  
  ; Create uninstaller
  WriteUninstaller "$INSTDIR\\uninstall.exe"
  WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\BlackjackCardCounter" \
                 "DisplayName" "Blackjack Card Counter"
  WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\BlackjackCardCounter" \
                 "UninstallString" "$\"$INSTDIR\\uninstall.exe$\""
  WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\BlackjackCardCounter" \
                 "DisplayIcon" "$INSTDIR\\BlackjackCardCounter.exe"
  WriteRegDWORD HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\BlackjackCardCounter" \
                   "NoModify" 1
  WriteRegDWORD HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\BlackjackCardCounter" \
                   "NoRepair" 1
SectionEnd

Section "Uninstall"
  ; Remove files and directories
  RMDir /r "$INSTDIR"
  
  ; Remove shortcuts
  Delete "$SMPROGRAMS\\BlackjackCardCounter\\Blackjack Card Counter.lnk"
  RMDir "$SMPROGRAMS\\BlackjackCardCounter"
  Delete "$DESKTOP\\Blackjack Card Counter.lnk"
  
  ; Remove uninstaller
  DeleteRegKey HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\BlackjackCardCounter"
SectionEnd
""")
    
    # Build the installer
    print("Building installer...")
    subprocess.check_call(["makensis", "installer/installer.nsi"])
    
    # Move the installer to the root directory
    if os.path.exists("BlackjackCardCounter_Setup.exe"):
        os.remove("BlackjackCardCounter_Setup.exe")
    shutil.move("installer/BlackjackCardCounter_Setup.exe", "./")
    
    print("\nBuild complete!")
    print("Installer created: BlackjackCardCounter_Setup.exe")

if __name__ == "__main__":
    create_installer()
